<a href="https://colab.research.google.com/github/ihwala/Hello/blob/main/Workshop8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5,5,100)
y1 = (5-x)/3
y2 = (5+x)/2
y3 = 3-x
fig, ax = plt.subplots()
ax.plot(x,y1, color='r')
ax.plot(x,y3, color='b')
ax.plot(x,y2, color='g')
ax.text(0.5,0.6, '
', color='r')
ax.text(-3,0.5,'
', color='g')
ax.text(1.2,2, '
', color='b')
ax.set_xlim(-4,4)
ax.set_ylim(-2,6)
ax.axvline(color='k',linewidth = 1)
ax.axhline(color='k',linewidth = 1)
ax.set_xticks(list(range(-4,5)))
ax.set_aspect('equal')
ax.grid(True,ls=':')
plt.xlabel("X")
plt.ylabel("Y")
plt.show()

SyntaxError: unterminated string literal (detected at line 11) (168664149.py, line 11)

In [ ]:

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5,5,100)
y1 = (3-2*x)/3
y2 = (6-4*x)/6
y3 = (3*x-1)/2
fig, ax = plt.subplots()
ax.plot(x,y1, color='r')
ax.plot(x,y3, color='b')
ax.plot(x,y2, color='g')
ax.text(0.5,0.6, '
', color='r')
ax.text(-3,0.5,'
', color='g')
ax.text(1.2,2, '
', color='b')
ax.set_xlim(-4,4)
ax.set_ylim(-2,6)
ax.axvline(color='k',linewidth = 1)
ax.axhline(color='k',linewidth = 1)
ax.set_xticks(list(range(-4,5)))
ax.set_aspect('equal')
ax.grid(True,ls=':')
plt.xlabel("X")
plt.ylabel("Y")
plt.show()



In [2]:
import numpy as np
mat1 = np.random.randint(0, 10, (2, 3))
mat2 = np.random.randint(0, 10, (2, 3))
mat3 = np.random.randint(0, 10, (2, 3))
res = mat1 - mat2 + mat3
print(mat1)
print(mat2)
print(mat3)
print(res)

[[6 2 7]
 [7 1 1]]
[[0 8 7]
 [1 2 9]]
[[3 7 5]
 [7 6 8]]
[[ 9  1  5]
 [13  5  0]]


In [ ]:

import numpy as np
mat = np.random.randint(1, 21, size=(4, 4))
print(mat)
inp = input("Enter a number : ")
if inp.isdigit():
    n = int(inp)
    cnt = np.count_nonzero(mat == n)
    if cnt > 0:
        print(f"The number {n} is found {cnt} time(s) in the matrix.")
    else:
        print(f"The number {n} is not found in the matrix.")
else:
    print("Invalid input!")

[[ 4 12  3 20]
 [17 14 17  3]
 [ 4 13 12  5]
 [ 9 19  8  4]]
