<a href="https://colab.research.google.com/github/ihwala/Hello/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(A)
print("Shape:", A.shape)
print("Dimensions:", A.ndim)
print("Data type:", A.dtype)
print("Size:", A.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Data type: int64
Size: 9


In [2]:

import numpy as np

A = np.ones((4,5)) * 3.0
print(A)


[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [3]:

import numpy as np

A = np.full((4,5), 3.0)
print(A)


[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [4]:

import numpy as np

A = np.diag([1,2,3,4])
print(A)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [5]:
import numpy as np

A = np.arange(20).reshape(4,5)
print("Original Matrix:\n", A)

B = A[:3, :3]
print("Sliced Matrix:\n", B)

Original Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sliced Matrix:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


In [6]:

import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1,1,1],
              [2,2,2]])

print(A + B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:

import numpy as np

def matrix_vector_mult(A, v):
    result = []
    for i in range(len(A)):
        sum = 0
        for j in range(len(v)):
            sum += A[i][j] * v[j]
        result.append(sum)
    return result

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]

v = [1,1,1]

print("Manual:", matrix_vector_mult(A, v))

# NumPy check
A_np = np.array(A)
v_np = np.array(v)

print("NumPy:", A_np.dot(v_np))

In [ ]:

import numpy as np

def matrix_mult(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

print("Manual:", matrix_mult(A,B))

# NumPy check
A_np = np.array(A)
B_np = np.array(B)

print("NumPy:\n", A_np.dot(B_np))


In [ ]:

import numpy as np

def is_symmetric(A):
    A = np.array(A)
    return np.array_equal(A, A.T)

A = [[1,2,3],
     [2,5,6],
     [3,6,9]]

print("Is symmetric?", is_symmetric(A))